POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste11",
    "email": "email11@email.com",
    "password": "23432535"
}

###

GET http://localhost:3003/user

###


POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "Efeito borboleta",
    "description": "Filme de suspence",
    "duration_in_minutes": 89,
    "year_of_release": 2010
}
